### ISSUE TITLE
"The uses of jQuery .queue and .dequeue()" cites outdated jQuery source code

### ISSUE THREAD

**Issue by alimony** [jquery/learn.jquery.com#289]
http://learn.jquery.com/effects/uses-of-queue-and-dequeue/

The second paragraph refers to the `.delay` implementation in the jQuery source code, but the code section is outdated, since the current implementation looks like this:

```javascript
// Based off of the plugin by Clint Helfers, with permission.
// http://blindsignals.com/index.php/2009/07/jquery-delay/
delay: function( time, type ) {
	time = jQuery.fx ? jQuery.fx.speeds[ time ] || time : time;
	type = type || "fx";

	return this.queue( type, function( next, hooks ) {
		var timeout = setTimeout( next, time );
		hooks.stop = function() {
			clearTimeout( timeout );
		};
	});
}
```

It's probably not a good idea to have an example based on source code that's going to change over time, but could a temporary solution be to replace the code section with an updated version of the implementation?

**Comment by arthurvr** [comment]
> It's probably not a good idea to have an example based on source code that's going to change over time, but could a temporary solution be to replace the code section with an updated version of the implementation?

<blockquote>We should probably just dumb down the implementation and create one that doesn't support changing the type.</blockquote>

We kind of have a similar function in [`queue-and-dequeue-explained.md`](https://github.com/jquery/learn.jquery.com/blob/master/page/effects/queue-and-dequeue-explained.md), so that will get done by https://github.com/jquery/learn.jquery.com/issues/289. I'll open a PR updating the function as it is right now, we can simplify the implementation with the other issue.

**Comment by disscfrench** [comment]
At the moment I am working at IBM who are in the process of buying a company. They have used a lot of the jquery plugins and, in some cases, have lifted code and inserted it into their software. I know most (if not all the plugins) are covered by the MIT/GPL licenses. My only worry is that some of these sites where the code was obtained no longer exist and do not make reference to the license or copyright status of the code. The question is can we create a single site with properly licensed code examples? Its a big deal this IBM are, quite rightly, weary of litigation over code ownership. :-)
