### ISSUE TITLE
Widget Factory tutorial content sort of duplicated

### ISSUE THREAD

**Issue by alimony** [jquery/learn.jquery.com#335]
These two sections are very similar:

http://learn.jquery.com/jquery-ui/widget-factory/how-to-use-the-widget-factory/

http://learn.jquery.com/plugins/stateful-plugins-with-widget-factory/

I think one of them should be merged into the other, or something.

**Comment by arthurvr** [comment]
Agree that big pieces are duplicate.

To me the piece in the `plugins` section must be removed, since there is a hole section about the widget factory in the `jquery-ui` part.

No additional content seems to live in there, so easyfix might be to to link up the widget factory section from `plugins/basic-plugin-creation/`. Thoughts?

**Comment by arthurvr** [comment]
I'm wondering what the appropriate place for this is. It seems like both UI and plugins related, so, maybe we can link up the page in the UI section from `plugins/`? Or vice-versa? The articles living in the UI section seem like a little more complete.

**Comment by arschmitz** [comment]
I would say it should be in UI over plugins. A link from plugins would be good though.

**Comment by arthurvr** [comment]
Agreed. I'll open a PR.
