### ISSUE TITLE
Intro to Custom Events: Uses API that no longer exists

### ISSUE THREAD

**Issue by outer89** [jquery/learn.jquery.com#475]
Hii!
I'm looking only now to jquery, and I was following your very nice tutorial.

wrt full example in http://learn.jquery.com/events/introduction-to-custom-events/ while triggering the call to twitter search api the following message is received:

jquery21009855909089092165_1393512219500({"errors":[{"message":"The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.","code":64}]});

the API are no more supported, it will be useful and nice to change the api version for having a good and full example working. This is one of the few complete example you have in your site under the learning center, and it will really be a pity to mess it up.

**Comment by gnarf** [comment]
I'm going to look closer at this soon and try to rewrite it, unless @arthurvr feels inspired and wants to take it before I get to it.

**Comment by arthurvr** [comment]
Thanks @gnarf!

**Comment by gnarf** [comment]
Looking at this again - I really think we can just get rid of the entire "sample application" --- The document up until then does a pretty good job of explaining it and also supports the conclusion.

**Comment by gnarf** [comment]
I mean http://learn.jquery.com/events/introduction-to-custom-events/#a-sample-application does this application actually provide anything concrete that I should try to reproduce in a new one?

**Comment by agcolom** [comment]
@gnarf I think it's not critical, but would be nice to have. If there's an example you can think of, it would be great to have that added here to replace the twitter example. One of the objectives for us is to have more "real world" examples, so that would fit nicely. Otherwise, I agree that the article is well written and explains the topic clearly.

**Comment by scottgonzalez** [comment]
A few comments about the article:

Using custom events with arbitrary names is dangerous as they may become standard in the future. Instead of `changeState` use something like `lightbulb:change`.

The sentence "If you're accustomed to object-oriented programming, you may find it useful to think of custom events as methods of objects" is pretty terrible advice. Events are not there for external users to trigger. They are not methods. In this sense, the article is fairly misleading, showing no real separation between who is listening for events and who is triggering events. The concept of a single "owner" of the event is not discussed. To show the confusion, we're attempting to separate the behavior between the switch and the lights, but an event (`click`) on the switch is directly triggering an event (`turnOn`/`turnOff`) on the lights. A lot of users end up writing code like this and then wonder why certain things don't work (because they're triggering events they don't own, thinking that the event is the cause of everything that happens when the event is normally triggered by the owner).

To be fair, the confusion starts with jQuery's built-in methods which are inverted from how the DOM works. In the DOM, a method like `.focus()` is actually a method that tells the element to take focus, which in turn triggers an event as the element tries to become focused. That is a very important difference from jQuery's `.focus()` which triggers and event and then detects if there was a native method that has an associated action.
