### ISSUE TITLE
Write the RequireJS dependency management and build system exploration promised

### ISSUE THREAD

**Issue by jgomo3** [jquery/learn.jquery.com#530]
https://github.com/jquery/learn.jquery.com/blob/d617895610e8c8a73c7dd34bb85a569a64582315/page/code-organization/concepts.md

**Comment by arthurvr** [comment]
PR: #609.

**Comment by jgomo3** [comment]
Although 7c3105ea33411d8b1ae318f7626a58cce60db667 resolves #609 I think it doen't fully resolve #530. That commit only adds a link to RequireJS site. This "issue" suggests" to write the needed to "explore the RequireJS dependency management and build system" as it is mentioned in the document "page/code-organization/concepts.md".

**Comment by arthurvr** [comment]
@jgomo3 We have limited resources, so it's better to link to good resources out of this site. We shouldn't make it harder for ourselfs by writing content that already exists elsewhere. If we need to cover everything where you can use jQuery with, we're going to have a hard time :)

The requireJS site itself has a section on using it together with jQuery, so that's enough for us. Doing more would be as good as duplicating content.

Also that sentence on our site doesn't suggest there's an article on requireJS. It suggests users to check out requireJS and its functionality, nothing more than that.

**Comment by arthurvr** [comment]
However I agree that the intro of the article needs some rewording.

**Comment by jgomo3** [comment]
I understand. Thank you.
