### ISSUE TITLE
Update the jQM article on custom themes with themeroller

### ISSUE THREAD

**Issue by agcolom** [jquery/learn.jquery.com#685]
We need to mention that we now only have 2 swatches. And change all refs to "c" to "e".

**Comment by VamsiSangam** [comment]
May I fix this issue?

**Comment by AurelioDeRosa** [comment]
Yes, feel free to give it a go.

**Comment by VamsiSangam** [comment]
I have tried the [ThemeRoller](http://themeroller.jquerymobile.com/) a bit and everything seems to be in accordance with its [documentation](https://github.com/jquery/learn.jquery.com/blob/master/page/jquery-mobile/theme-roller.md#creating-a-custom-theme-with-themeroller). I don't understand where the issue is. Can you please help me out a bit? 😃

**Comment by agcolom** [comment]
@VamsiSangam The library only comes with 2 defined themes: A and B (light and dark). However, the documentation still refers to 5 default swatches in jQuery Mobile (A, B, C, D and E) as this was written before 1.4 came out. The ThemeRoller part is most probably fine, it is only the references to the default themes in jQuery Mobile that are affected by the change. Also, the docs makes a reference to a default theme C for count bubble in listviews which is also no longer the case, since we only have 2 themes, A and B.
