### ISSUE TITLE
Doc on document.ready should indicate if multiple declarations will conflict

### ISSUE THREAD

**Issue by David-dp-** [jquery/learn.jquery.com#719]
In page learn.jquery.com/page/using-jquery-core/document-ready.md there is no indication whether a later declaration of document.ready (perhaps in a library) would overwrite or compose an earlier declaration (perhaps in another library). If it would overwrite, it would be helpful to indicate what error might be reported.

**Comment by dmethvin** [comment]
To keep the learning documentation lean I think it's better to only introduce the concepts here and refer people to the [API documentation](http://api.jquery.com/ready/) for details. Otherwise we are duplicating too much and when things change or need clarification we have to do it in multiple places.

**Comment by AurelioDeRosa** [comment]
I agree with Dave about the duplication of information. I think that adding a link to the API page should be enough.

**Comment by David-dp-** [comment]
Thanks for pointing out that there's a separate API reference. It appeared
to me that I was already reading the API reference.

**Comment by David-dp-** [comment]
FWIW, the API page you provided doesn't answer my question, either. I can't
find any widget on the page to provide feedback, but if there is one,
please let me know.

**Comment by dmethvin** [comment]
I'll  clarify when it's rewritten in https://github.com/jquery/api.jquery.com/issues/964
